AllCops:
  Exclude:
    - "Appraisals"
    - "gemfiles/**/*"
    - "rein.gemspec"

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 28

Metrics/BlockLength:
  ExcludedMethods:
    - describe

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "spec/**/*"
  Max: 11

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/Documentation:
  Exclude:
    - "spec/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
